language: android
android:
        components:
                - platform-tools
                - android-28
                - extra-android-m2repository
script:
        - ./gradlew build
        - ./gradlew build jacocoTestReport
before_install:
        - chmod +x gradlew
        - yes | sdkmanager "platform-tools" "tools" "platforms;android-28" "extras;android;m2repository"
branches:
        only:
                - master
after_success:
        - bash <(curl -s https://codecov.io/bash)

