language: android
android:
        components:
                - platform-tools
                - build-tools-23.0.1
                - android-28
                - extra-android-m2repository
script:
        - ./gradlew build
before_install:
        - chmod +x gradlew
        - yes | sdkmanager "platform-tools" "tools" "platforms;android-28" "extras;android;m2repository"
branches:
        only:
                - master
